controllers/GameController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\components\GeneratorHelper;
use achertovsky\math\models\Math;
use yii\data\ActiveDataProvider;

class GameController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Displays Game homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $session = Yii::$app->session;
        if ($session->has('count')) {
            $step = $session->get('count');
            //if current step > maxStepCount
            if ($step > Yii::$app->params["maxStepCount"]) {
                return $this->redirect(['result']);
            }
        } else {
            $step = 1;
            $session->set('count', $step);
            //clear all previous results
            Math::deleteAll();
        }

        $model = new Math();
        $model->a = GeneratorHelper::getNumber();
        $model->b = GeneratorHelper::getNumber();
        $model->operation = GeneratorHelper::getOperation();

        return $this->render('index', [
            'model' => $model,
            'step' => $step
        ]);
    }

    /**
     * Calculate action.
     * @param integer $isAjax , type of request
     * @return Response|string
     */
    public function actionCalculate($isAjax = null)
    {
        $model = new Math();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->operation == "+") {
                $model->add();
            }
            if ($model->operation == "-") {
                $model->sub();
            }
            if ($model->validate()) {
                $session = Yii::$app->session;
                $step = $session->get('count') + 1;
                $session->set('count', $step);
                if ($isAjax != 1) {
                    return $this->redirect(['show', 'id' => $model->id]);
                } else {
                    $this->layout = false;
                    return $this->render('show', [
                        'model' => $model,
                        'step' => $step
                    ]);
                }
            }
        }

    }


    /**
     * Show action.
     * @param integer $id Math model
     * @return Response|string
     */
    public function actionShow($id)
    {
        $model = Math::findOne($id);
        $session = Yii::$app->session;
        $step = $session->get('count');

        return $this->render('show', [
            'model' => $model,
            'step' => $step
        ]);
    }

    /**
     * Result action.
     *
     * @return Response|string
     */
    public function actionResult()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Math::find()
        ]);

        $score = Math::getScore();
        return $this->render('result', [
            'dataProvider' => $dataProvider,
            'score' => $score
        ]);
    }

}

views/game/index.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\bootstrap\Html;


/* @var $this yii\web\View */

$this->title = 'Math game';
?>
    <div class="row">
        <div class="col-md-6">
            <h1>Simple math game</h1>
        </div>
        <div class="col-md-6"><h1>Step <?= $step ?> of <?= Yii::$app->params["maxStepCount"] ?></h1></div>
    </div>
    <div class="row ajax-settings">
        <div class="col-md-6">Use Ajax <?= Html::checkbox('is_ajax', false, ['id' => 'is_ajax']) ?> </div>
    </div>
    <div class="body-content">
        <?php $form = ActiveForm::begin([
            'action' => Url::to(['game/calculate']),
            'id' => 'submitForm',
            'options' => [
                'class' => 'form-inline',
            ]
        ]); ?>
        <div class="row question">
            <div class="col-md-6">
                <div class="col-md-6"><?= $model->a ?> <?= $model->operation ?> <?= $model->b ?> = ?</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-6">
                    <?= $form->field($model, 'user_result')
                        ->textInput()->label(false); ?>
                </div>
                <div class="col-md-6">
                    <?= Html::submitButton('<span class="glyphicon glyphicon-ok-circle"></span> Submit', [
                        'id' => 'btn_submit',
                        'class' => 'btn btn-success'
                    ]) ?>
                </div>
            </div>
        </div>
        <?= $form->field($model, 'a')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'operation')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'b')->hiddenInput()->label(false) ?>
        <?php ActiveForm::end(); ?>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-6" id="answer"></div>
            </div>
        </div>
    </div>
<?php
$js = <<<JS

        //$("#submitForm").submit(function (event) {
 $(document).on('beforeSubmit', '#submitForm', function (event, messages, errorAttributes) {
    //if Ajax flag set to on
    if ($("#is_ajax").is(':checked')) {
        $.ajax({
               type: "POST",
               url: $("#submitForm").attr('action')+'&isAjax=1',
               data: $("#submitForm").serialize(),
               success: function(data)
               {
                   $("#answer").html(data);
                   $("#btn_submit").attr("disabled","disabled");
               }
        });

        return false;
    }
  });
JS;

$this->registerJs($js);
?>

views/game/result.php
<?php
use yii\grid\GridView;

?>
Your score is <?= round($score, 2) ?> %
<?= GridView::widget([
    'id' => 'table',
    'dataProvider' => $dataProvider,
    'showFooter' => true,
    'columns' => [
        [
            'class' => 'yii\grid\SerialColumn',
            'contentOptions' => ['style' => 'width:50px;']
        ],
        'task',
        'result',
        'user_result',
    ],
]); ?>

views/game/show.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>
<?= $model->task . ' = ' . $model->user_result ?>
<?php
if ($model->result != $model->user_result) {
    ?>
    <a class="glyphicon glyphicon-remove"></a> INCORRECT
<?php
} else {
    ?>
    <a class="glyphicon glyphicon-ok"></a> CORRECT
<?php
}
?>
<br> Correct result is : <?= $model->result ?>
<br>
<br>
<?= Html::a('Next', Url::to([
    ($step >= (Yii::$app->params["maxStepCount"] + 1)) ? 'game/result' : 'game/index'
]), [
    'class' => 'btn btn-sm btn-success'
]) ?>